[project]
site_name = "Frikortoppslag API"
site_description = "API-dokumentasjon for oppslag av egenandelsfritakstatus"

extra_css = ["stylesheets/extra.css"]

nav = [
    { "Oversikt" = "index.md" },
    { "Kryptering av request" = "kryptering_av_request.md" },
    { "Endepunkter" = [
        { "Hent egenandelsfritakstatus" = "endepunkter/hent_frikortstatus.md" },
        { "Klientstatus" = "endepunkter/klientstatus.md" },
        { "Hent JWK" = "endepunkter/jwk.md" },
    ] },
    { "Generelt" = [
        { "Kodeverk" = "generelt/kodeverk.md" },
        { "Begrepsliste" = "generelt/begrepsliste.md" },
        { "JSON-konvensjoner" = "generelt/json_konvensjoner.md" },
        { "FAQ" = "generelt/faq.md" },
        { "Endringslogg" = "generelt/endringslogg.md" },
    ] },
]

[project.theme]
language = "nb"

features = [
    "content.code.copy",
    "search.highlight",
    "navigation.sections",
    "navigation.top"
]

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
toggle.icon = "lucide/sun"
toggle.name = "Bytt til mørk modus"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Bytt til lys modus"
